name: kanboard
services:
  app:
    image: ${KANBOARD_IMAGE:-kanboard/kanboard:latest}
    container_name: kanboard
    restart: always
    environment:
      - PUID=100
      - PGID=101
    expose:
     - "80"
     # - "443:443"
    volumes:
     - /mnt/hdd_data/volumes/kanboard_data:/var/www/app/data
     - /mnt/hdd_data/volumes/kanboard_plugins:/var/www/app/plugins
     # - certs:/etc/nginx/ssl
    environment:
     - PLUGIN_INSTALLER=true # Swap to true to enable web based plugin installation
    networks:
      - shared_network
volumes:
  data:
    driver: local
  plugins:
    driver: local

networks:
  shared_network:
    driver: bridge
    external: true
    name: nginx_gateway_shared_network